apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: configmapmake-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: configmapmake-controller-crole
subjects:
- kind: ServiceAccount
  name: configmapmake-controller
  namespace: configmap-operator

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmapmake-controller
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: configmapmake-controller-role
subjects:
- kind: ServiceAccount
  name: configmapmake-controller
  namespace: configmap-operator
