apiVersion: v1
kind: Service
metadata:
  name: configmapmake-controller
  namespace: configmap-operator
  labels:
    control-plane: configmapmake-controller
spec:
  selector:
    control-plane: configmapmake-controller
  ports:
    - name: http-metrics
      port: 9091
      targetPort: http-metrics
